name: TechFlow CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev jest-environment-jsdom
    
    - name: Run tests
      run: npm test

  build-and-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t techflow-app .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8080:80 --name test-app techflow-app
        sleep 10
        curl -f http://localhost:8080 || exit 1
        curl -f http://localhost:8080/styles.css || exit 1
        curl -f http://localhost:8080/script.js || exit 1
        docker stop test-app && docker rm test-app

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
